### ISSUE TITLE
TeamBuilderComponent.html:1 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked.

### ISSUE THREAD

**Issue by schmist** [schmist/dimensions-builder#2]
The following Angular error, triggered when navigating to the team builder, needs fixing:

`ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: ''. Current value: '[object Object],`

**Comment by IRQs** [comment]
The fix applied in https://github.com/schmist/dimensions-builder/commit/7218560900484b768e4986109af1bd901fca5783 is only a temporary workaround based on insights provided by [this Stack Overflow entry](https://stackoverflow.com/questions/42190290/expression-has-changed-after-it-was-checked-when-child-component-emits-on-ngon).

The root cause of the problem is probably due to https://github.com/schmist/dimensions-builder/blob/7218560900484b768e4986109af1bd901fca5783/src/app/components/ability-select.component.ts#L123 which causes the _skills_ model of the parent (TeamBuilderComponent) to be changed in the _ngOnInit_ method of the child component (AbilitySelectComponent). Unfortunately, this occurs during the same change detection cycle as the first initialization of the (empty) model and causes the error described above. This behavior has recently changed in Angular 4.2.x and is discussed in angular/angular#17572.
